"""The only hand-written input in the entire graph pipeline — a business
decision about which corpus categories relate to which, expressed as a plain
Python list (ARCHITECTURE.md §4.1, §7). Everything else about the Neo4j
graph is generated by running ingestion/ingest.py; no Cypher is ever typed
by hand into Neo4j Browser or anywhere else.
"""

CATEGORY_RELATIONS = [
    ("ORDER", "CANCEL"),
    ("ORDER", "DELIVERY"),
    ("ORDER", "REFUND"),
    ("ORDER", "INVOICE"),
    ("DELIVERY", "SHIPPING"),
    ("PAYMENT", "INVOICE"),
    ("PAYMENT", "REFUND"),
    ("CANCEL", "REFUND"),
    ("ACCOUNT", "SUBSCRIPTION"),
    ("ACCOUNT", "PAYMENT"),
    ("FEEDBACK", "CONTACT"),
]
